#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""UI アイコン（ドット絵 SVG）の定義と、index.html への埋め込み。

デザイン規約 D-4/(1)：
  UI アイコンに絵文字を使わない。16×16 の 1px グリッドに完全に乗せた
  矩形の集合として描き、<symbol> + <use> で定義を1箇所にまとめる。

ここでは絵を「1文字＝1ドット」の16行×16列の文字絵として持つ。
矩形は横方向に連続した同色ドットをまとめて1つの <rect> にする（＝出力が小さくなる）。
色は :root の var(--i-*) を参照するので、CSS 側だけで色を変えられる。

使い方:
    python3 tools/icons.py            # index.html の ICONS:BEGIN〜END を書き換える
    python3 tools/icons.py --preview  # dev/icons.html（16倍拡大の確認ページ）も作る
"""
import io, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INDEX = os.path.join(ROOT, "index.html")
PREVIEW = os.path.join(ROOT, "dev", "icons.html")

# 絵の具。k は輪郭（すべての要素に濃い輪郭線を入れる＝コミカルさの要）。
INK = "k"
PALETTE = {
    "k": "var(--i-ink)",
    "w": "var(--i-white)",    "W": "var(--i-white-d)",
    "s": "var(--i-steel)",    "S": "var(--i-steel-d)",
    "g": "var(--i-gold)",     "G": "var(--i-gold-d)",
    "r": "var(--i-red)",      "R": "var(--i-red-d)",
    "c": "var(--i-cyan)",     "C": "var(--i-cyan-d)",
    "t": "var(--i-stone)",    "T": "var(--i-stone-d)",
    "b": "var(--i-wood)",     "B": "var(--i-wood-d)",
    "v": "var(--i-violet)",   "V": "var(--i-violet-d)",
    "n": "var(--i-green)",    "N": "var(--i-green-d)",
}

ICONS = {}

# ── ダイヤ（通貨）。上面の明部＋下半分の暗部で2階調。
ICONS["gem"] = ("ダイヤ", """
................
.......kk.......
......kcck......
.....kcccck.....
....kwccccck....
...kwwcccccck...
..kcccccccccck..
..kCCCCCCCCCCk..
...kCCCCCCCCk...
....kCCCCCCk....
.....kCCCCk.....
......kCCk......
.......kk.......
................
................
................
""")

# ── 剣（攻撃・プレイ）。刃は明部/暗部の2列、鍔と柄頭が金、握りが木。
ICONS["sword"] = ("剣", """
.......kk.......
......ksSk......
.....kssSSk.....
.....kssSSk.....
.....kssSSk.....
.....kssSSk.....
.....kssSSk.....
.....kssSSk.....
..kkkkkkkkkkkk..
..kggggggggggk..
..kkkkkbbkkkkk..
......kbbk......
......kbbk......
.....kkbbkk.....
.....kggggk.....
.....kkkkkk.....
""")

# ── 指令旗（集合地点）。竿＋なびく旗。
ICONS["flag"] = ("指令旗", """
..kkk...........
..kbkkkkkkkkkkk.
..kbkrrrrrrrrrk.
..kbkrrrrrrrrrk.
..kbkRRRRRRRk...
..kbkRRRRRk.....
..kbkRRRk.......
..kbkk..........
..kbk...........
..kbk...........
..kbk...........
..kbk...........
..kbk...........
.kkbkk..........
.kbbbk..........
.kkkkk..........
""")

# ── 撤退（白旗）。指令旗と同じ形・色だけ違う＝2つで1組に見えるようにしてある。
ICONS["retreat"] = ("撤退", """
..kkk...........
..kbkkkkkkkkkkk.
..kbkwwwwwwwwwk.
..kbkwwwwwwwwwk.
..kbkWWWWWWWk...
..kbkWWWWWk.....
..kbkWWWk.......
..kbkk..........
..kbk...........
..kbk...........
..kbk...........
..kbk...........
..kbk...........
.kkbkk..........
.kbbbk..........
.kkkkk..........
""")

# ── 錬成（強化パネル）。フラスコ。
ICONS["flask"] = ("錬成", """
................
.....kkkkkk.....
.....kwwwwk.....
......kwwk......
......kwwk......
......kwwk......
.....kwwwwk.....
....kwwwwwwk....
...kwwvvvvwwk...
..kwwvvvvvvwwk..
..kwvvvvvvvvwk..
..kwvvvvvvvvwk..
..kwVVVVVVVVwk..
...kwVVVVVVwk...
....kkkkkkkk....
................
""")

# ── 盾（防御）。
ICONS["shield"] = ("盾", """
................
..kkkkkkkkkkkk..
..kssssggssssk..
..kssssggssssk..
..kSsssggsssSk..
..kSsssggsssSk..
..kSsssggsssSk..
...kSssggssSk...
...kSssggssSk...
....kSsggsSk....
.....kSggSk.....
......kggk......
.......kk.......
................
................
................
""")

# ── 銀行（引継ぎ銀行）。切妻屋根＋柱。
ICONS["bank"] = ("銀行", """
................
.......kk.......
.....kkggkk.....
...kkggggggkk...
..kggggggggggk..
..kkkkkkkkkkkk..
..kttttttttttk..
..kTttTttTttTk..
..kTttTttTttTk..
..kTttTttTttTk..
..kTttTttTttTk..
..kTttTttTttTk..
..kttttttttttk..
..kTTTTTTTTTTk..
..kkkkkkkkkkkk..
................
""")

# ── 実績（宝具庫・トロフィー）。
ICONS["trophy"] = ("実績", """
................
..kkkkkkkkkkkk..
..kggggggggggk..
.kkkGGGGGGGGkkk.
.kGkGGGGGGGGkGk.
.kGkGGGGGGGGkGk.
.kkkGGGGGGGGkkk.
...kGGGGGGGGk...
....kGGGGGGk....
.....kGGGGk.....
......kGGk......
......kGGk......
.....kkGGkk.....
...kggggggggk...
...kkkkkkkkkk...
................
""")

# ── 岩（素材・石スライム）。
ICONS["rock"] = ("岩", """
................
................
.....kkkkkk.....
....kttttttk....
...kttttttttk...
..kttttttTTttk..
..kttttTTTTttk..
.kttttTTTTttttk.
.kttTTtTTTTtttk.
.kttTTtTTTTTttk.
.kTTTTTTTTTTTTk.
.kTTTTTTTTTTTTk.
..kTTTTTTTTTTk..
..kkkkkkkkkkkk..
................
................
""")

# ── 譲渡（書き出し）。箱＋上向きの矢。
ICONS["export"] = ("譲渡", """
.......kk.......
......kwwk......
.....kwwwwk.....
....kwwwwwwk....
...kwwwwwwwwk...
...kkkkwwkkkk...
......kwwk......
......kwwk......
................
..kkkkkkkkkkkk..
..kbbbbbbbbbbk..
..kbBBBBBBBBbk..
..kbBBBBBBBBbk..
..kbbbbbbbbbbk..
..kkkkkkkkkkkk..
................
""")


def grid(art, palette=None):
    """文字絵を行の配列にし、正方形であることと色記号が定義済みであることを検査する。
    大きさは行数から決める（UI アイコンは16、盤面のタイルは15、ちびは10 など）。"""
    palette = palette or PALETTE
    rows = [r for r in art.strip("\n").split("\n")]
    n = len(rows)
    for i, r in enumerate(rows):
        assert len(r) == n, "%d行目が%d文字でない: %d (%r)" % (i, n, len(r), r)
        for ch in r:
            assert ch == "." or ch in palette, "未定義の色記号 %r" % ch
    return rows


# ══════════════════════════════════════════════════════════════════
# 発注3-b：残りの絵文字の置き換え（2026-09-10）
# 棚卸しの結果、意味が重複しているものは1つにまとめてある。
#   ✅と✔ → check ／ 🥚と🍼 → egg ／ 🏅と🎉 → medal ／ 💰と💹 → coin
#   宝具36個は kind（blade/shield/orb/…）で束ねる。個別の絵は持たない。
# 逆に、状態が反対のもの（🔊/🔇・📤/📥）は別の絵が要るので2つ持つ。
# ══════════════════════════════════════════════════════════════════

ICONS["cart"] = ("お買い物", """
................
................
.kk.............
.kgk............
.kkkkkkkkkkkkkk.
..kgggggggggk...
..kgGGGGGGGgk...
..kgGGGGGGGgk...
...kGGGGGGGk....
....kkkkkkk.....
....k.....k.....
...kwk...kwk....
....k.....k.....
................
................
................
""")

ICONS["gear"] = ("設定", """
................
................
.....kkkkkk.....
...kkksssskkk...
...kssssssssk...
.kkksssssssskkk.
.kSSsskkkkssSSk.
.kSSsskkkkssSSk.
.kkksssssssskkk.
...kssssssssk...
...kkksssskkk...
.....kkkkkk.....
................
................
................
................
""")

ICONS["dna"] = ("交配", """
................
................
................
..kkkk....kkkk..
.kvvvvk..kvvvvk.
.kvkkvkkkkvkkvk.
.kvkkvkkkkvkkvk.
.kvvvvk..kvvvvk.
..kkkk....kkkk..
................
................
................
................
................
................
................
""")

ICONS["coin"] = ("ゴールド", """
................
................
....kkkkkkkk....
..kkggggggggkk..
.kkggggggggggkk.
.kggggkGGkggggk.
.kgggkGGGGkgggk.
.kgggkGGGGkgggk.
.kggggkGGkggggk.
.kkggggggggggkk.
..kkggggggggkk..
....kkkkkkkk....
................
................
................
................
""")

ICONS["skull"] = ("敗北", """
................
................
...kkkkkkkkkk...
..kwwwwwwwwwwk..
..kwwwwwwwwwwk..
..kwkkwwwwkkwk..
..kwkkwwwwkkwk..
..kwwwwwwwwwwk..
..kwwwwkkwwwwk..
...kwwwwwwwwk...
....kkkkkkkk....
....kwkkkkwk....
....kkkkkkkk....
................
................
................
""")

ICONS["arena"] = ("コロシアム", """
................
....kkkkkkkk....
..kkTTTTTTTTkk..
.kkTTTTTTTTTTkk.
.kTTkkkkkkkkTTk.
.kTTkwwwwwwkTTk.
.kTTkwwwwwwkTTk.
.kTTkwwwwwwkTTk.
.kTTkwwwwwwkTTk.
.kTTkwwwwwwkTTk.
.kkkkkkkkkkkkkk.
.kTTTTTTTTTTTTk.
.kkkkkkkkkkkkkk.
................
................
................
""")

ICONS["lock"] = ("未解放", """
................
................
.....kkkkkk.....
....kkSSSSkk....
....kSkkkkSk....
....kSk..kSk....
..kkkkkkkkkkkk..
..kggggggggggk..
..kgggkkkkgggk..
..kgggkkkkgggk..
..kggggkkggggk..
..kggggggggggk..
..kkkkkkkkkkkk..
................
................
................
""")

ICONS["sound"] = ("音あり", """
................
................
................
.........kk.....
.......kkss.....
.kkkkkkssss.k.k.
.kssssssssk.k.k.
.kssssssssk.k.k.
.kkkkkkssss.k.k.
.......kkss.....
.........kk.....
................
................
................
................
................
""")

ICONS["mute"] = ("消音", """
................
................
................
.........kk.....
.......kkss.....
.kkkkkkssss.k.k.
.kssssssssk..k..
.kssssssssk.k.k.
.kkkkkkssss.....
.......kkss.....
.........kk.....
................
................
................
................
................
""")

ICONS["pause"] = ("ポーズ", """
................
................
..kkkk....kkkk..
..kwwk....kwwk..
..kwwk....kwwk..
..kwwk....kwwk..
..kwwk....kwwk..
..kwwk....kwwk..
..kwwk....kwwk..
..kwwk....kwwk..
..kwwk....kwwk..
..kkkk....kkkk..
................
................
................
................
""")

ICONS["target"] = ("追尾", """
................
................
.....kkkkkk.....
...kkrrrrrrkk...
..kkrrwwwwrrkk..
..krrwwwwwwrrk..
..krwwwrrwwwrk..
..krwwrrrrwwrk..
..krwwrrrrwwrk..
..krwwwrrwwwrk..
..krrwwwwwwrrk..
..kkrrwwwwrrkk..
...kkrrrrrrkk...
.....kkkkkk.....
................
................
""")

ICONS["depth"] = ("深度", """
................
................
................
................
....kkkkkkkk....
..kkVVVVVVVVkk..
.kVVVVVVVVVVVVk.
.kVVVVVVVVVVVVk.
..kkVVVVVVVVkk..
....kkkkkkkk....
................
................
................
................
................
................
""")

ICONS["anvil"] = ("鍛冶場", """
................
................
................
...kkkkkkkkkk...
..kSSSSSSSSSSk..
..kSSSSSSSSSSk..
...kkkSSSSkkk...
.....kSSSSk.....
.....kSSSSk.....
....kkSSSSkk....
...kSSSSSSSSk...
...kkkkkkkkkk...
................
................
................
................
""")

ICONS["import"] = ("受け取り", """
......kwwk......
......kwwk......
...kkkkwwkkkk...
...kwwwwwwwwk...
....kwwwwwwk....
.....kwwwwk.....
......kwwk......
.......kk.......
................
..kkkkkkkkkkkk..
..kbbbbbbbbbbk..
..kbBBBBBBBBbk..
..kbBBBBBBBBbk..
..kbbbbbbbbbbk..
..kkkkkkkkkkkk..
................
""")

ICONS["copy"] = ("コピー", """
................
....kkkkkkkkkk..
....kwwwwwwwwk..
....kwwwwwwwwk..
..kkkkkkkkkkwk..
..kwwwwwwwwkwk..
..kwwwwwwwwkwk..
..kwwwwwwwwkkk..
..kwwwwwwwwk....
..kwwwwwwwwk....
..kwwwwwwwwk....
..kkkkkkkkkk....
................
................
................
................
""")

ICONS["check"] = ("完了", """
................
................
.............kk.
............knk.
...........knk..
.kk.......knk...
.knk.....knk....
..knk...knk.....
...knk.knk......
....knknk.......
.....knk........
......k.........
................
................
................
................
""")

ICONS["warn"] = ("警告", """
................
.......kk.......
.......kk.......
......krrk......
......krrk......
.....krrrrk.....
.....krkkrk.....
....krrkkrrk....
....krrkkrrk....
...krrrkkrrrk...
...krrrkkrrrk...
..krrrrrrrrrrk..
..krrrrkkrrrrk..
..kkkkkkkkkkkk..
................
................
""")

ICONS["wrench"] = ("修復", """
................
...kk......kk...
..kSSk....kSSk..
..kSSSkkkkSSSk..
..kSSSSSSSSSSk..
...kSSSSSSSSk...
....kkSSSSkk....
......kSSk......
......kSSk......
......kSSk......
......kSSk......
......kSSk......
......kkkk......
................
................
................
""")

ICONS["medal"] = ("最高記録", """
................
...kk......kk...
...kwk....kwk...
...kwwk..kwwk...
....kwwkkwwk....
.....kkkkkk.....
....kkggggkk....
...kggggggggk...
..kgggkGGkgggk..
..kggkGGGGkggk..
..kggkGGGGkggk..
..kgggkGGkgggk..
...kggggggggk...
....kkggggkk....
.....kkkkkk.....
................
""")

ICONS["egg"] = ("繁殖", """
................
................
......kkkk......
....kkwwwwkk....
...kwwwwwwwwk...
..kwwwwwwwwwwk..
..kwwwwwwwwwwk..
..kwwwwwwwwwwk..
..kwwWWWWWWwwk..
...kwWWWWWWWk...
....kkWWWWkk....
......kkkk......
................
................
................
................
""")

ICONS["gate"] = ("門", """
................
..kkkkkkkkkkkk..
..kttttttttttk..
..ktTTTTTTTTtk..
..ktTwwwwwwTtk..
..ktTwWWWWwTtk..
..ktTwWWWWwTtk..
..ktTwWWWWwTtk..
..ktTwWWWWwTtk..
..ktTwWWWWwTtk..
..ktTwWWWWwTtk..
..ktTwWWWWwTtk..
..ktTTTTTTTTtk..
..kkkkkkkkkkkk..
................
................
""")

ICONS["ticket"] = ("コード", """
................
................
................
..kkkkkkkkkkkk..
..kggggggggggk..
..kggkkkkkkggk..
..kggkGGGGkggk..
..kggkGGGGkggk..
..kggkkkkkkggk..
..kggggggggggk..
..kkkkkkkkkkkk..
................
................
................
................
................
""")

ICONS["trash"] = ("破棄", """
................
......kkkk......
...kkkkkkkkkk...
...kwwwwwwwwk...
....kkkkkkkk....
....kwkkkkwk....
....kwkkkkwk....
....kwkkkkwk....
....kwkkkkwk....
....kwwwwwwk....
....kkkkkkkk....
................
................
................
................
................
""")

ICONS["fire"] = ("最大", """
................
.......kk.......
......krrk......
......krrk......
.....krrrrk.....
.....krrrrk.....
....krrrrrrk....
....krggggrk....
...krrggggrrk...
...krrggggrrk...
...krrrggrrrk...
....krrrrrrk....
.....kkkkkk.....
................
................
................
""")

ICONS["bolt"] = ("レバレッジ", """
................
.........kk.....
........kgk.....
.......kgk......
......kgk.......
.....kgkkkk.....
....kggggggk....
.....kkkkgk.....
.......kgk......
......kgk.......
.....kgk........
.....kk.........
................
................
................
................
""")

ICONS["pick"] = ("掘削", """
................
..kk........kk..
..kSkk....kkSk..
...kSSkkkkSSk...
....kSSSSSSk....
.....kkbbkk.....
......kbbk......
......kbbk......
......kbbk......
......kbbk......
......kbbk......
......kbbk......
......kkkk......
................
................
................
""")

ICONS["eye"] = ("探索", """
................
................
................
.....kkkkkk.....
...kkwwwwwwkk...
..kwwwwkkwwwwk..
.kwwwkkkkkkwwwk.
.kwwkkkkkkkkwwk.
.kwwwkkkkkkwwwk.
..kwwwwkkwwwwk..
...kkwwwwwwkk...
.....kkkkkk.....
................
................
................
................
""")

# ── 宝具は36個あるが、絵は kind（系統）ごとに1つで足りる。
#    blade→sword / shield→shield / stone→rock / crystal・shard→shard を流用するので、
#    ここで新しく描くのは4つだけ。
ICONS["orb"] = ("宝珠", """
................
................
.....kkkkkk.....
...kkvvvvvvkk...
..kvvvvvvvvvvk..
.kvvwwvvvvvvvvk.
.kvvwwvvvvvvvvk.
.kvvvvvvvvvvvvk.
.kvvvvvvvvvvvvk.
..kvvvvvvvvvvk..
...kkvvvvvvkk...
.....kkkkkk.....
................
................
................
................
""")

ICONS["relic"] = ("遺物", """
................
.....kkkkkk.....
.....kbbbbk.....
......kbbk......
.....kbbbbk.....
....kbbbbbbk....
...kbbbbbbbbk...
...kbBBBBBBbk...
...kbBBBBBBbk...
....kbBBBBbk....
.....kkbbkk.....
.....kbbbbk.....
.....kkkkkk.....
................
................
................
""")

ICONS["crown"] = ("冠", """
................
................
................
..kk..kkkk..kk..
..kgk.kggk.kgk..
..kggkkggkkggk..
..kggggggggggk..
..kgGGGGGGGGgk..
..kgGGGGGGGGgk..
..kkkkkkkkkkkk..
................
................
................
................
................
................
""")

ICONS["charm"] = ("護符", """
................
....kk....kk....
...kwk....kwk...
...kwk....kwk...
....kwk..kwk....
.....kwkkwk.....
......kwwk......
.....kkwwkk.....
....kvvvvvvk....
....kvVVVVvk....
....kvVVVVvk....
.....kvvvvk.....
......kkkk......
................
................
................
""")

ICONS["shard"] = ("かけら", """
................
................
......kkkk......
.....kcccck.....
....kcccccck....
...kcccccccck...
...kCCCCCCCCk...
...kCCCCCCCCk...
....kCCCCCCk....
.....kCCCCk.....
......kCCk......
.......kk.......
................
................
................
................
""")

ICONS["scepter"] = ("杖", """
................
.......kk.......
......kggk......
.....kggggk.....
.....kggggk.....
......kggk......
.......kk.......
......kbbk......
......kbbk......
......kbbk......
......kbbk......
......kbbk......
......kbbk......
......kkkk......
................
................
""")


def center(name, rows):
    """絵を箱の左右の中心に寄せる。

    光の向きで左右非対称になるのは構わないが、塗りの外接矩形の中心が箱の中心と
    ずれていると、文字と並べたときだけ傾いて見える。原因が分かりにくいので機械で直す。

    ただし **寄せられない場合がある**。箱が16なら絵の幅も偶数でないと中心に載らない
    （幅11の絵は中心が 7.5 か 8.5 にしかならない）。その時は1px 足すか削るしかないので、
    黙って寄せずに落とす。"""
    n = len(rows)
    xs = [x for r in rows for x, c in enumerate(r) if c != "."]
    if not xs:
        return rows
    lo, hi = min(xs), max(xs)
    w = hi - lo + 1
    assert (n - w) % 2 == 0, (
        "%s: 絵の幅が %d なので %d の箱の中心に載らない（幅を1px 足すか削る）" % (name, w, n))
    shift = (n - w) // 2 - lo
    if shift == 0:
        return rows
    out = []
    for r in rows:
        body = r[lo:hi + 1]
        out.append("." * ((n - w) // 2) + body + "." * (n - w - (n - w) // 2))
    return out


def paths(rows, palette=None):
    """横に連続した同色ドットを1本の矩形サブパスにし、色ごとに1つの <path> へまとめる。
    <rect> を1つずつ並べるより出力が 1/4 以下になる（見た目は同じ・1px グリッドのまま）。"""
    palette = palette or PALETTE
    n = len(rows)
    runs = {}
    for y, row in enumerate(rows):
        x = 0
        while x < n:
            ch = row[x]
            if ch == ".":
                x += 1
                continue
            w = 1
            while x + w < n and row[x + w] == ch:
                w += 1
            runs.setdefault(ch, []).append("M%d %dh%dv1h-%dz" % (x, y, w, w))
            x += w
    # 輪郭を最初に置く（重なっても輪郭が消えないように、以降の色が上に乗る）
    order = sorted(runs, key=lambda c: (c != INK, c))
    return ['<path fill="%s" d="%s"/>' % (palette[ch], "".join(runs[ch])) for ch in order]


def board_symbols():
    """盤面の絵（モンスター4種・あくま部屋）を UI アイコンとしても使う。

    強化パネルやショップに出るモンスターの印は、盤面に立っている個体と同じ絵であるべき
    （別々に描くと、同じものが2つの顔を持つ）。なので絵は tools/sprites.py 側に1つだけ置き、
    ここでは色を付けて <symbol> にするだけにする。
    ※ import をこの関数の中でするのは、sprites.py が icons.py を読むため（相互参照になる）。"""
    import sprites
    out = {}
    # 体つき4 × 素材4 = 16通り。純種（例：石スライム）も「自分の体つき＋自分の素材」なので
    # 同じ作り方で出せる。異種交配の印を絵文字の連結で作っていた旧実装はこれで要らなくなる。
    for form, (label, art) in sprites.FORMS.items():
        for coat, mat in sprites.MATS.items():
            pal = {"k": "var(--i-ink)", "1": mat[1], "2": mat[2], "w": "var(--i-white)"}
            name = label if coat == form else (mat[0] + label)
            out["mon-%s-%s" % (form, coat)] = (name, art, pal)
    ca = sprites.CASTLE
    out["castle"] = ("あくま部屋", ca, {
        "k": "var(--i-ink)", "R": "var(--i-red)", "V": "#2a1330", "g": "var(--i-gold)"})
    return out


def sprite():
    parts = []
    items = [(k, l, a, None) for k, (l, a) in ICONS.items()]
    items += [(k, l, a, pal) for k, (l, a, pal) in board_symbols().items()]
    for key, label, art, pal in items:
        rows = center(key, grid(art, pal))
        n = len(rows)
        rs = paths(rows, pal)
        parts.append('  <symbol id="i-%s" viewBox="0 0 %d %d"><title>%s</title>%s</symbol>'
                     % (key, n, n, label, "".join(rs)))
    return ('<svg id="icoSprite" aria-hidden="true" focusable="false"\n'
            '     width="0" height="0" style="position:absolute"\n'
            '     shape-rendering="crispEdges" xmlns="http://www.w3.org/2000/svg">\n'
            + "\n".join(parts) + "\n</svg>")


BEGIN = "<!-- ICONS:BEGIN tools/icons.py が生成。手で編集しない -->"
END = "<!-- ICONS:END -->"


def write_index():
    s = io.open(INDEX, encoding="utf-8").read()
    block = BEGIN + "\n" + sprite() + "\n" + END
    if BEGIN in s:
        s = re.sub(re.escape(BEGIN) + r"[\s\S]*?" + re.escape(END), lambda m: block, s, count=1)
    else:
        s = s.replace("<body>\n", "<body>\n\n    " + block.replace("\n", "\n    ") + "\n", 1)
    io.open(INDEX, "w", encoding="utf-8").write(s)
    print("index.html にスプライトを書き込んだ（%d 種・%d bytes）" % (block.count("<symbol"), len(block)))


def write_preview():
    src = io.open(INDEX, encoding="utf-8").read()
    tokens = re.search(r"/\* ===== アイコンの絵の具[\s\S]*?\*/\s*", src)
    root = re.search(r":root \{[\s\S]*?\}", src).group(0)
    face = re.search(r"@font-face \{[\s\S]*?\}", src).group(0)
    allicons = [(k, v[0]) for k, v in ICONS.items()] + \
               [(k, v[0]) for k, v in board_symbols().items()]
    cells = "\n".join(
        '<figure><svg class="big" viewBox="0 0 16 16" shape-rendering="crispEdges">'
        '<use href="#i-%s"/></svg><figcaption>%s<br><small>#i-%s</small></figcaption></figure>'
        % (k, label, k) for k, label in allicons)
    inline = "\n".join(
        '<span class="row"><svg class="ico"><use href="#i-%s"/></svg>%s のテキストと並べたとき</span>'
        % (k, label) for k, label in allicons)
    html = """<!DOCTYPE html><html lang="ja"><head><meta charset="UTF-8">
<title>アイコン確認</title><style>
%s
%s
body{background:var(--c-bg);color:var(--c-text);font-family:var(--font-ui);margin:0;padding:24px}
h1{font-size:24px;margin:0 0 24px}
h2{font-size:12px;color:var(--c-text-sub);margin:32px 0 12px;letter-spacing:2px}
.sheet{display:flex;flex-wrap:wrap;gap:12px}
figure{margin:0;text-align:center}
.big{width:96px;height:96px;image-rendering:pixelated;background:var(--c-bg-game);
     border:1px solid var(--c-frame-faint)}
figcaption{font-size:12px;margin-top:8px;color:var(--c-text-sub)}
.ico{width:16px;height:16px;vertical-align:-3px;margin-right:8px}
.row{display:block;font-size:12px;margin:8px 0}
.onlight{background:var(--c-text);padding:8px;display:inline-block}
</style></head><body>
%s
<h1>UI アイコン（16×16 ドット絵）</h1>
<h2>― 16倍に拡大 ―</h2>
<div class="sheet">%s</div>
<h2>― 実寸（16px）で文字と並べたところ ―</h2>
%s
<h2>― 実寸を明るい地の上に置いたところ（輪郭の効きを見る） ―</h2>
<div class="onlight">%s</div>
</body></html>""" % (
        face, root,
        re.search(r'<svg id="icoSprite"[\s\S]*?</svg>', src).group(0),
        cells, inline,
        "".join('<svg class="ico"><use href="#i-%s"/></svg>' % k for k, _ in allicons))
    os.makedirs(os.path.dirname(PREVIEW), exist_ok=True)
    io.open(PREVIEW, "w", encoding="utf-8").write(html)
    print("確認ページ: dev/icons.html")


if __name__ == "__main__":
    write_index()
    if "--preview" in sys.argv:
        write_preview()
